## Assignment 6: Project Reflection
ITMG 4J
Britney Dang

In [3]:
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# Load the CSV file into a DataFrame
file_path = r'C:/Users/dangb/Downloads/enhanced_box_office_data(2000-2024)u.csv'
movies = pd.read_csv(file_path)

## Data Analysis

In [5]:
# Looking at the data
display(movies)

,Rank,Release Group,$Worldwide,$Domestic,Domestic %,$Foreign,Foreign %,Year,Genres,Rating,Vote_Count,Original_Language,Production_Countries
0,1,Mission: Impossible II,546388108.0,215409889.0,39.4,330978219.0,60.6,2000,"Adventure, Action, Thriller",6.126/10,6741.0,en,United States of America
1,2,Gladiator,460583960.0,187705427.0,40.8,272878533.0,59.2,2000,"Action, Drama, Adventure",8.217/10,19032.0,en,"United Kingdom, United States of America"
2,3,Cast Away,429632142.0,233632142.0,54.4,196000000.0,45.6,2000,"Adventure, Drama",7.663/10,11403.0,en,United States of America
3,4,What Women Want,374111707.0,182811707.0,48.9,191300000.0,51.1,2000,"Comedy, Romance",6.45/10,3944.0,en,"United Kingdom, United States of America"
4,5,Dinosaur,349822765.0,137748063.0,39.4,212074702.0,60.6,2000,"Animation, Family, Adventure",6.544/10,2530.0,en,United States of America
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,196,Devara Part 1,7361414.0,5600000.0,76.1,1761414.0,23.9,2024,"Action, Drama",7.0/10,30.0,te,India
4996,197,Kolpaçino 4 4'lük,7343114.0,0.0,0.0,7343114.0,100.0,2024,Comedy,4.0/10,4.0,tr,Turkey
4997,198,Lim Young Woong: Im Hero the Stadium,7305588.0,0.0,0.0,7305588.0,100.0,2024,"Music, Documentary",0.0/10,0.0,ko,South Korea
4998,199,Yolo,7241561.0,2001584.0,27.6,5239977.0,72.4,2024,"Drama, Comedy, Action",6.3/10,70.0,zh,China
4999,200,Sight,7206741.0,7206741.0,100.0,0.0,0.0,2024,"Drama, History",6.0/10,23.0,en,United States of America

In [10]:
# How many rows and columns there are
print(movies.shape)

(5000, 13)

In [12]:
# How many NA values there are
print(movies.isna().sum())
print("")

# Total number of NA values in the entire DataFrame
total_na = movies.isna().sum().sum()
print("The total NA values is", total_na)

Rank                      0
Release Group             0
$Worldwide                0
$Domestic                 0
Domestic %                0
$Foreign                  0
Foreign %                 0
Year                      0
Genres                  178
Rating                  170
Vote_Count              170
Original_Language       170
Production_Countries    200
dtype: int64

The total NA values is 888

### Recommendation

After assesing the data, I've decided to implement the recommendation I have made in my Assignment 3: a baby project.

The recommendation included splitting up the 'Production_Countries' and 'Genres' into primary and secondary columns so that you are able to pull data from specfic data points (specfic production countries/genres)

In [20]:
# Function to split the 'Production_Countries' column into main and secondary countries
def split_production_countries(countries):
    if pd.isna(countries):
        return (None, None)  # No production countries
    country_list = countries.split(",")  # Split countries by commas
    main_country = country_list[0].strip()  # The first country is the main one
    secondary_countries = ", ".join(country_list[1:]).strip() if len(country_list) > 1 else None
    return (main_country, secondary_countries)

# Apply the function to the 'Production_Countries' column
movies[['Main_Production_Country', 'Secondary_Production_Countries']] = movies['Production_Countries'].apply(split_production_countries).apply(pd.Series)

# Display the first few rows of the DataFrame to verify the changes
movies.head()

,Rank,Release Group,$Worldwide,$Domestic,Domestic %,$Foreign,Foreign %,Year,Genres,Rating,Vote_Count,Original_Language,Production_Countries,Main_Production_Country,Secondary_Production_Countries,Main_Genre,Secondary_Genres
0,1,Mission: Impossible II,546388108.0,215409889.0,39.4,330978219.0,60.6,2000,"Adventure, Action, Thriller",6.126/10,6741.0,en,United States of America,United States of America,None,Adventure,"Action, Thriller"
1,2,Gladiator,460583960.0,187705427.0,40.8,272878533.0,59.2,2000,"Action, Drama, Adventure",8.217/10,19032.0,en,"United Kingdom, United States of America",United Kingdom,United States of America,Action,"Drama, Adventure"
2,3,Cast Away,429632142.0,233632142.0,54.4,196000000.0,45.6,2000,"Adventure, Drama",7.663/10,11403.0,en,United States of America,United States of America,None,Adventure,Drama
3,4,What Women Want,374111707.0,182811707.0,48.9,191300000.0,51.1,2000,"Comedy, Romance",6.45/10,3944.0,en,"United Kingdom, United States of America",United Kingdom,United States of America,Comedy,Romance
4,5,Dinosaur,349822765.0,137748063.0,39.4,212074702.0,60.6,2000,"Animation, Family, Adventure",6.544/10,2530.0,en,United States of America,United States of America,None,Animation,"Family, Adventure"

In [21]:
# Function to split the 'Genres' column into main and secondary genres
def split_genres(genres):
    if pd.isna(genres):
        return (None, None)  # No genres available
    genre_list = genres.split(",")  # Split genres by commas
    main_genre = genre_list[0].strip()  # The first genre is the main one
    secondary_genres = ", ".join(genre_list[1:]).strip() if len(genre_list) > 1 else None
    return (main_genre, secondary_genres)

# Apply the function to the 'Genres' column
movies[['Main_Genre', 'Secondary_Genres']] = movies['Genres'].apply(split_genres).apply(pd.Series)

# Display the first few rows of the DataFrame to verify the changes
movies.head()

,Rank,Release Group,$Worldwide,$Domestic,Domestic %,$Foreign,Foreign %,Year,Genres,Rating,Vote_Count,Original_Language,Production_Countries,Main_Production_Country,Secondary_Production_Countries,Main_Genre,Secondary_Genres
0,1,Mission: Impossible II,546388108.0,215409889.0,39.4,330978219.0,60.6,2000,"Adventure, Action, Thriller",6.126/10,6741.0,en,United States of America,United States of America,None,Adventure,"Action, Thriller"
1,2,Gladiator,460583960.0,187705427.0,40.8,272878533.0,59.2,2000,"Action, Drama, Adventure",8.217/10,19032.0,en,"United Kingdom, United States of America",United Kingdom,United States of America,Action,"Drama, Adventure"
2,3,Cast Away,429632142.0,233632142.0,54.4,196000000.0,45.6,2000,"Adventure, Drama",7.663/10,11403.0,en,United States of America,United States of America,None,Adventure,Drama
3,4,What Women Want,374111707.0,182811707.0,48.9,191300000.0,51.1,2000,"Comedy, Romance",6.45/10,3944.0,en,"United Kingdom, United States of America",United Kingdom,United States of America,Comedy,Romance
4,5,Dinosaur,349822765.0,137748063.0,39.4,212074702.0,60.6,2000,"Animation, Family, Adventure",6.544/10,2530.0,en,United States of America,United States of America,None,Animation,"Family, Adventure"

### Aggregating Data

In [27]:
# Filter movies with Production_Countries as 'United States of America' and Main_Genre as 'Action'
us_action_movies = movies[(movies['Main_Production_Country'] == 'United States of America') & 
                          (movies['Main_Genre'] == 'Action')]

# Aggregate Data (Example: Count, Sum, Mean, etc.)
us_action_summary = us_action_movies.agg({
    '$Worldwide': ['sum', 'mean'],   # Total and average worldwide box office
    '$Domestic': ['sum', 'mean'],    # Total and average domestic revenue
    '$Foreign': ['sum', 'mean'],     # Total and average foreign revenue
})

# Display the aggregated results
print(us_action_summary)

        $Worldwide     $Domestic      $Foreign
sum   8.919356e+10  3.506339e+10  5.413017e+10
mean  3.013296e+08  1.184574e+08  1.828722e+08

In [29]:
print("Total Action Movies from USA:", us_action_movies.shape[0])

Total Action Movies from USA: 296

***References***

ChatGPT was used as a tool to help understand code and help fix problems that arised throughout the process.